### ISSUE TITLE
Please include lightbulb models supported in your README

### ISSUE THREAD

**Issue by truedat101** [nkaminski/csrmesh#1]
The details provided "Feight Electric" HomeBrite Smart LED Bulb helps narrow down, but due to differences in global markets, it might be helpful to list the model numbers and names:

"A19 Household", Item No A0M800/827/LED/HBR (for example)

**Comment by nkaminski** [comment]
Change implemented. Thanks for the feedback!

**Comment by truedat101** [comment]
It's surprising, but these bulbs are cheaper than the equivalent Zigbee (a Cree for example is around $16).

**Comment by nkaminski** [comment]
Yeah, can't beat the cost. :) Got mine at Menards for $10 after rebate.
