### ISSUE TITLE
Work with the B10 version (E12)

### ISSUE THREAD

**Issue by ghost** [nkaminski/csrmesh#14]
Hello,

Thank you for this script.

You can add on the README that this bulb work too :)

http://www.canadiantire.ca/en/pdp/feit-electric-homebrite-bluetooth-smart-light-bulb-40w-0522370p.html#srp

Are they a way to get the state of the bulb? (on, off or the level)

Thanks !

Tube

**Comment by nkaminski** [comment]
There does not appear to be any type of read support in the HomeBrite bulbs that I am aware of. Even the included app does not appear to be capable of reading the state of a bulb.
