### ISSUE TITLE
Noob question: Teptron Move BTLE device ID

### ISSUE THREAD

**Issue by mlava** [nkaminski/csrmesh#19]
Hi.
Sorry to be a pain.
Can you please advise how to obtain the device ID for my Move devices?
Cheers!

**Comment by t0mas** [comment]
Do you mean the parameter for --dest or for --objid?

The dest parameter is the hardware ID of the device, which you can find if you search for Bluetooth devices. You should see a device named "CSRMesh" (at least that is the name my device uses), the hardware address of that is the input for the dest parameter.

The objid is something we haven't really figured out yet. In all devices I've seen it is numbered in the order in which the devices joined the network in the official app. So the first device has objid 1.

**Comment by nkaminski** [comment]
As the author of this application, the objid is a sequential count
starting at 1 that is incremented in the order that devices are added to
the network for device IDs and incremented in the order that groups are
created for group IDs.

**Comment by mlava** [comment]
Thank you both
