### ISSUE TITLE
Possibility of pull state?

### ISSUE THREAD

**Issue by clemon79** [nkaminski/csrmesh#21]
Is there any possibility in the future of a csrmesh-cli function that will poll a light for its current state (brightness values, RGB, etc) rather than just pushing settings to it, or is that just not how the protocol works? It seems like this functionality is the missing link in being able to really incorporate this strongly into home automation projects. If I could occasionally poll the light and be able to update sliders on Home Assistant, that would be marvelous.

**Comment by nkaminski** [comment]
With the current CSR mesh devices that I've interacted with, which currently has been limited to Feit homebrite smart bulbs, there is no support that I am aware of at the protocol level for such. Even the official app does not support pulling the state of existing bulbs.

Therefore unless someone can present a case, along with the accompanying BTLE network traffic of state information being pulled from a CSRmesh device, I'm afraid such support is not possible.

Nash Kaminski

On June 30, 2017 11:48:53 PM CDT, clemon79 <notifications@github.com> wrote:
>Is there any possibility in the future of a csrmesh-cli function that
>will poll a light for its current state (brightness values, RGB, etc)
>rather than just pushing settings to it? It seems like this
>functionality is the missing link in being able to really incorporate
>this strongly into home automation projects. If I could occasionally
>poll the light and be able to update sliders on Home Assistant, that
>would be marvelous.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nkaminski/csrmesh/issues/21

-- 
Sent from my Android device with K-9 Mail.

**Comment by clemon79** [comment]
Ah, cool. And yeah, I notice that the app doesn't poll state, but I was hopeful that was just because the app is crappy in so many other ways. :)

I really appreciate your hard work here!
