### ISSUE TITLE
Is it possible to GET information from move blinds?

### ISSUE THREAD

**Issue by Swiftnesses** [nkaminski/csrmesh#23]
I noticed the app is already getting the LUX level from the blind controller, obviously the UART document lists all the commands... Can we use somehow access these items?

**Comment by nkaminski** [comment]
I do not have a MOVE unit, however I may be able to help if you provide a bluetooth packet capture   of the traffic transacted by the official app as well as the PIN used when generating such traffic. Using Androids HCI snoop log functionality in the developer tools is usually the easiest way to obtain such. If you want to look into it more yourself, there are a few (undocumented at moment) functions in crypto.py that allow you to decrypt and read the contents of CSRMesh packets.
