### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mjg59** [nkaminski/csrmesh#29]
I finally figured out how to read data from the Avion switches in order to determine their state (it turns out to be as simple as enabling notifications), but I need to be able to decrypt packets in order to do that. Since the responses are sent from the devices themselves I need https://github.com/nkaminski/csrmesh/pull/28 to do this. Any chance you can cut a new release so I can update my dependencies? Thanks!

**Comment by nkaminski** [comment]
Will do this weekend.

**Comment by mjg59** [comment]
Thank you!

**Comment by nkaminski** [comment]
New release pushed to PyPi at https://pypi.org/project/csrmesh/0.10.0/

**Comment by mjg59** [comment]
Thanks!
