### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by voxadam** [nkaminski/csrmesh#8]
Great project; it should make writing an interface to my GE/Jasco Smart Switch go much smoother. I also wanted to point you in the direction of a repo here on GitHub that you may find interesting [sshhsh/csrmesh_2_0_node](https://github.com/sshhsh/csrmesh_2_0_node). The docs directory is full of information that you might find useful. Personally I'm steering clear of the applications, include, and libraries directories as I'm reasonably sure they contain code which if I were to read would contaminate any open source software I might want to release in the future. 

Thanks again.

**Comment by nkaminski** [comment]
Thanks, will look at (carefully as well)!
